# Site settings
author: Curtis Laurence Chadwell
title: The Evolution Of A Bartender
header-img: img/home-bg.png
email: laurencechadwell@gmail.com
copyright_name: Curtis Laurence Chadwell
description: > # this means to ignore newlines until "baseurl:"
  Watch me grow
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  curchadw

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
